"""Create bookmarks table

Revision ID: 49745ac4590e
Revises: 940f189d9623
Create Date: 2026-04-05 12:07:07.974435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49745ac4590e'
down_revision = '940f189d9623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_context().dialect.has_table(op.get_context().bind, 'bookmarks'):
        op.create_table('bookmarks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('serial_number', sa.String(), nullable=True),
        sa.Column('game_id', sa.String(length=4), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
