"""Add PTBR to Videos and Banners

Revision ID: 940f189d9623
Revises: 862433351ed0
Create Date: 2026-03-08 13:52:03.381069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940f189d9623'
down_revision = '862433351ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ptbr', sa.String(length=102), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ptbr', sa.String(length=102), nullable=True))

    op.execute("""
               UPDATE banners
               SET name_ptbr = 'None';
               """)

    op.execute("""
               UPDATE videos
               SET name_ptbr = 'None';
               """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('name_ptbr')

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_column('name_ptbr')

    # ### end Alembic commands ###
