"""updated initial migration

Revision ID: a1cab16c8e0c
Revises: 
Create Date: 2026-08-31 20:03:06.666446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1cab16c8e0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_japanese', sa.String(length=102), nullable=True),
    sa.Column('name_english', sa.String(length=102), nullable=True),
    sa.Column('name_german', sa.String(length=102), nullable=True),
    sa.Column('name_french', sa.String(length=102), nullable=True),
    sa.Column('name_spanish', sa.String(length=102), nullable=True),
    sa.Column('name_italian', sa.String(length=102), nullable=True),
    sa.Column('name_dutch', sa.String(length=102), nullable=True),
    sa.Column('name_ptbr', sa.String(length=102), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('game_id', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('game_id', sa.String(length=6), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('recommendation_percent', sa.Integer(), nullable=True),
    sa.Column('appeal', sa.Integer(), nullable=True),
    sa.Column('gaming_mood', sa.Integer(), nullable=True),
    sa.Column('friend_or_alone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('time_played',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('game_id', sa.String(length=6), nullable=True),
    sa.Column('times_played', sa.Integer(), nullable=True),
    sa.Column('time_played', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('title_en', sa.String(length=512), nullable=False),
    sa.Column('synopsis_en', sa.String(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('game_type', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('developer', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('release_month', sa.Integer(), nullable=True),
    sa.Column('release_day', sa.Integer(), nullable=True),
    sa.Column('rating_type', sa.String(length=32), nullable=True),
    sa.Column('rating_value', sa.String(length=32), nullable=True),
    sa.Column('wifi_players', sa.Integer(), nullable=True),
    sa.Column('input_players', sa.Integer(), nullable=True),
    sa.Column('input_controls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('gamespy_id', sa.String(), server_default='', nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false::boolean'), nullable=True),
    sa.Column('wfc_observations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('is_supported', sa.Integer(), server_default=sa.text('0::integer'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_japanese', sa.String(length=102), nullable=True),
    sa.Column('name_english', sa.String(length=102), nullable=True),
    sa.Column('name_german', sa.String(length=102), nullable=True),
    sa.Column('name_french', sa.String(length=102), nullable=True),
    sa.Column('name_spanish', sa.String(length=102), nullable=True),
    sa.Column('name_italian', sa.String(length=102), nullable=True),
    sa.Column('name_dutch', sa.String(length=102), nullable=True),
    sa.Column('name_ptbr', sa.String(length=102), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('video_type', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('titles')
    op.drop_table('time_played')
    op.drop_table('recommendations')
    op.drop_table('bookmarks')
    op.drop_table('banners')
    # ### end Alembic commands ###
